const express = require("express");
const path = require("path");
const fs = require("fs");
const crypto = require("crypto");
const { Pool } = require("pg");
const cloudinary = require("cloudinary").v2;

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ extended: true, limit: "10mb" }));
app.use(express.static(path.join(__dirname, "public")));

const SESSION_SECRET =
  process.env.SESSION_SECRET || "CHANGE_THIS_SESSION_SECRET";
const ADMIN_USER = process.env.ADMIN_USER || "SMADMIN";
const ADMIN_PASS = process.env.ADMIN_PASS || "SM2728";

if (!process.env.DATABASE_URL) {
  console.error("ERROR: DATABASE_URL is missing.");
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
  max: 5
});

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
});

const defaultSettings = {
  shopName: "SM Online Shop",
  tagline: "Style • Comfort • Confidence ♥",
  phone1: "01827872334",
  phone2: "01886995687",
  facebook: "",
  currency: "BDT"
};

const ORDER_STATUSES = [
  "Pending",
  "Confirmed",
  "Processing",
  "Shipped",
  "Delivered",
  "Cancelled"
];

const PAYMENT_STATUSES = [
  "Pending",
  "Paid",
  "Failed",
  "Refunded"
];

function cleanText(value, fallback = "") {
  if (value === undefined || value === null) return fallback;
  return String(value).trim();
}

function positiveNumber(value, fallback = 0) {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function nonNegativeInt(value, fallback = 0) {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(0, Math.floor(n));
}

function makeProductId() {
  // Product IDs are TEXT on purpose. This prevents bigint/sequence errors
  // and is compatible with both old numeric IDs and new IDs.
  return "P" + Date.now().toString(36).toUpperCase() +
    crypto.randomBytes(3).toString("hex").toUpperCase();
}

function makeOrderId() {
  return "SM" + Date.now().toString(36).toUpperCase() +
    crypto.randomBytes(3).toString("hex").toUpperCase();
}

function makeCustomerId() {
  return "C" + Date.now().toString(36).toUpperCase() +
    crypto.randomBytes(3).toString("hex").toUpperCase();
}

function safeJsonParse(value, fallback = null) {
  try {
    if (value === null || value === undefined) return fallback;
    if (typeof value === "object") return value;
    return JSON.parse(value);
  } catch {
    return fallback;
  }
}

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
/* =========================================================
   DATABASE INITIALIZATION
   ========================================================= */

async function initDatabase() {
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    /* ---------------- STORE SETTINGS ---------------- */
    await client.query(`
      CREATE TABLE IF NOT EXISTS store_settings (
        id INTEGER PRIMARY KEY DEFAULT 1,
        shop_name TEXT NOT NULL DEFAULT 'SM Online Shop',
        tagline TEXT NOT NULL DEFAULT 'Style • Comfort • Confidence ♥',
        phone1 TEXT NOT NULL DEFAULT '01827872334',
        phone2 TEXT NOT NULL DEFAULT '01886995687',
        facebook TEXT NOT NULL DEFAULT '',
        currency TEXT NOT NULL DEFAULT 'BDT',
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    /* ---------------- PRODUCTS ----------------
       IMPORTANT:
       id is TEXT, not BIGINT/SERIAL.
       This removes the sequence overflow and bigint parsing problems.
    ------------------------------------------------ */
    await client.query(`
      CREATE TABLE IF NOT EXISTS products (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        category TEXT NOT NULL DEFAULT 'General',
        price NUMERIC(12,2) NOT NULL DEFAULT 0,
        old_price NUMERIC(12,2) NOT NULL DEFAULT 0,
        discount NUMERIC(6,2) NOT NULL DEFAULT 0,
        stock INTEGER NOT NULL DEFAULT 0,
        image TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    /* Convert old numeric/bigint product IDs to TEXT.
       Existing numeric IDs remain unchanged as strings.
    */
    const productIdType = await columnType("products", "id");

    if (
      productIdType &&
      productIdType !== "text" &&
      productIdType !== "character varying"
    ) {
      await client.query(`
        ALTER TABLE products
        ALTER COLUMN id DROP DEFAULT
      `);

      await client.query(`
        ALTER TABLE products
        ALTER COLUMN id TYPE TEXT
        USING id::text
      `);
    }

    /* Product IDs are generated by Node.js.
       PostgreSQL must NOT generate them using a sequence.
    */
    await client.query(`
      ALTER TABLE products
      ALTER COLUMN id DROP DEFAULT
    `);

    /* Add columns that older versions may not have. */
    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS name TEXT
    `);

    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'General'
    `);

    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS price NUMERIC(12,2) DEFAULT 0
    `);

    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS old_price NUMERIC(12,2) DEFAULT 0
    `);

    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS discount NUMERIC(6,2) DEFAULT 0
    `);

    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT 0
    `);

    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS image TEXT DEFAULT ''
    `);

    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW()
    `);

    await client.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()
    `);

    /* Repair NULL values safely. */
    await client.query(`
      UPDATE products
      SET category = 'General'
      WHERE category IS NULL
    `);

    await client.query(`
      UPDATE products
      SET price = 0
      WHERE price IS NULL
    `);

    await client.query(`
      UPDATE products
      SET old_price = price
      WHERE old_price IS NULL
    `);

    await client.query(`
      UPDATE products
      SET discount = 0
      WHERE discount IS NULL
    `);

    await client.query(`
      UPDATE products
      SET stock = 0
      WHERE stock IS NULL
    `);

    await client.query(`
      UPDATE products
      SET image = ''
      WHERE image IS NULL
    `);

    await client.query(`
      UPDATE products
      SET created_at = NOW()
      WHERE created_at IS NULL
    `);

    await client.query(`
      UPDATE products
      SET updated_at = NOW()
      WHERE updated_at IS NULL
    `);

    /* Make old empty product names safe. */
    await client.query(`
      UPDATE products
      SET name = 'Unnamed Product'
      WHERE name IS NULL OR BTRIM(name) = ''
    `);

    /* ---------------- ORDERS ---------------- */
    await client.query(`
      CREATE TABLE IF NOT EXISTS orders (
        id TEXT PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        customer JSONB NOT NULL DEFAULT '{}'::jsonb,
        items JSONB NOT NULL DEFAULT '[]'::jsonb,
        total NUMERIC(12,2) NOT NULL DEFAULT 0,
        payment_method TEXT NOT NULL DEFAULT 'cod',
        status TEXT NOT NULL DEFAULT 'Pending',
        payment_status TEXT NOT NULL DEFAULT 'Pending',
        stock_restored BOOLEAN NOT NULL DEFAULT FALSE,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    /* Convert old order IDs to TEXT. */
    const orderIdType = await columnType("orders", "id");

    if (
      orderIdType &&
      orderIdType !== "text" &&
      orderIdType !== "character varying"
    ) {
      await client.query(`
        ALTER TABLE orders
        ALTER COLUMN id DROP DEFAULT
      `);

      await client.query(`
        ALTER TABLE orders
        ALTER COLUMN id TYPE TEXT
        USING id::text
      `);
    }

    /* Orders are also generated by Node.js. */
    await client.query(`
      ALTER TABLE orders
      ALTER COLUMN id DROP DEFAULT
    `);

    /* Add missing order columns for old databases. */
    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW()
    `);

    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS customer JSONB DEFAULT '{}'::jsonb
    `);

    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS items JSONB DEFAULT '[]'::jsonb
    `);

    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS total NUMERIC(12,2) DEFAULT 0
    `);

    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'cod'
    `);

    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pending'
    `);

    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'Pending'
    `);

    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS stock_restored BOOLEAN DEFAULT FALSE
    `);

    await client.query(`
      ALTER TABLE orders
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()
    `);

    /* Repair order NULL values. */
    await client.query(`
      UPDATE orders
      SET customer = '{}'::jsonb
      WHERE customer IS NULL
    `);

    await client.query(`
      UPDATE orders
      SET items = '[]'::jsonb
      WHERE items IS NULL
    `);

    await client.query(`
      UPDATE orders
      SET total = 0
      WHERE total IS NULL
    `);

    await client.query(`
      UPDATE orders
      SET payment_method = 'cod'
      WHERE payment_method IS NULL
    `);

    await client.query(`
      UPDATE orders
      SET status = 'Pending'
      WHERE status IS NULL
    `);

    await client.query(`
      UPDATE orders
      SET payment_status = 'Pending'
      WHERE payment_status IS NULL
    `);

    await client.query(`
      UPDATE orders
      SET stock_restored = FALSE
      WHERE stock_restored IS NULL
    `);

    await client.query(`
      UPDATE orders
      SET created_at = NOW()
      WHERE created_at IS NULL
    `);

    await client.query(`
      UPDATE orders
      SET updated_at = NOW()
      WHERE updated_at IS NULL
    `);

    /* ---------------- CUSTOMERS ---------------- */
    await client.query(`
      CREATE TABLE IF NOT EXISTS customers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL DEFAULT '',
        phone TEXT NOT NULL DEFAULT '',
        address TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    const customerIdType = await columnType("customers", "id");

    if (
      customerIdType &&
      customerIdType !== "text" &&
      customerIdType !== "character varying"
    ) {
      await client.query(`
        ALTER TABLE customers
        ALTER COLUMN id DROP DEFAULT
      `);

      await client.query(`
        ALTER TABLE customers
        ALTER COLUMN id TYPE TEXT
        USING id::text
      `);
    }

    await client.query(`
      ALTER TABLE customers
      ALTER COLUMN id DROP DEFAULT
    `);

    await client.query(`
      INSERT INTO store_settings
        (id, shop_name, tagline, phone1, phone2, facebook, currency)
      VALUES
        (1, $1, $2, $3, $4, $5, $6)
      ON CONFLICT (id) DO NOTHING
    `, [
      defaultSettings.shopName,
      defaultSettings.tagline,
      defaultSettings.phone1,
      defaultSettings.phone2,
      defaultSettings.facebook,
      defaultSettings.currency
    ]);

    await client.query("COMMIT");

    console.log("Database initialized successfully.");
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("Database initialization error:", error);
    throw error;
  } finally {
    client.release();
  }
}
if (!ORDER_STATUSES.includes(newStatus)) {
      return res.status(400).json({ error: "Invalid order status" });
    }

    await client.query("BEGIN");

    const orderResult = await client.query(
      `
      SELECT
        id::text AS id,
        created_at AS "createdAt",
        customer,
        items,
        total::float AS total,
        payment_method AS "paymentMethod",
        status,
        payment_status AS "paymentStatus",
        stock_restored
      FROM orders
      WHERE id = $1
      FOR UPDATE
      `,
      [orderId]
    );

    if (!orderResult.rows.length) {
      await client.query("ROLLBACK");
      return res.status(404).json({ error: "Order not found" });
    }

    const order = orderResult.rows[0];

    if (!isValidStatusTransition(order.status, newStatus)) {
      await client.query("ROLLBACK");
      return res.status(400).json({
        error:
          `Cannot change order status from ${order.status} to ${newStatus}`
      });
    }

    if (newStatus === "Cancelled") {
      await restoreOrderStock(client, order);
    }

    const updated = await client.query(
      `
      UPDATE orders
      SET status = $1,
          updated_at = NOW()
      WHERE id = $2
      RETURNING
        id::text AS id,
        created_at AS "createdAt",
        customer,
        items,
        total::float AS total,
        payment_method AS "paymentMethod",
        status,
        payment_status AS "paymentStatus",
        stock_restored AS "stockRestored"
      `,
      [newStatus, orderId]
    );

    await client.query("COMMIT");

    res.json({
      ok: true,
      order: updated.rows[0]
    });
  } catch (error) {
    await client.query("ROLLBACK").catch(() => {});
    console.error("Update order status error:", error);

    res.status(500).json({
      error: error.message || "Could not update order status"
    });
  } finally {
    client.release();
  }
});

/* =========================================================
   PUBLIC CANCEL ORDER
   ========================================================= */

app.put("/api/orders/:id/cancel", async (req, res) => {
  const client = await pool.connect();

  try {
    const orderId = cleanText(req.params.id);

    if (!orderId) {
      return res.status(400).json({ error: "Order ID is required" });
    }

    await client.query("BEGIN");

    const result = await client.query(
      `
      SELECT
        id::text AS id,
        created_at AS "createdAt",
        customer,
        items,
        total::float AS total,
        payment_method AS "paymentMethod",
        status,
        payment_status AS "paymentStatus",
        stock_restored
      FROM orders
      WHERE id = $1
      FOR UPDATE
      `,
      [orderId]
    );

    if (!result.rows.length) {
      await client.query("ROLLBACK");
      return res.status(404).json({ error: "Order not found" });
    }

    const order = result.rows[0];

    if (order.status === "Cancelled") {
      await client.query("ROLLBACK");
      return res.json({
        ok: true,
        message: "Order is already cancelled",
        order
      });
    }

    if (order.status === "Delivered") {
      await client.query("ROLLBACK");
      return res.status(400).json({
        error: "Delivered order cannot be cancelled"
      });
    }

    await restoreOrderStock(client, order);

    const updated = await client.query(
      `
      UPDATE orders
      SET status = 'Cancelled',
          updated_at = NOW()
      WHERE id = $1
      RETURNING
        id::text AS id,
        created_at AS "createdAt",
        customer,
        items,
        total::float AS total,
        payment_method AS "paymentMethod",
        status,
        payment_status AS "paymentStatus",
        stock_restored AS "stockRestored"
      `,
      [orderId]
    );

    await client.query("COMMIT");

    res.json({
      ok: true,
      order: updated.rows[0]
    });
  } catch (error) {
    await client.query("ROLLBACK").catch(() => {});
    console.error("Customer cancel order error:", error);

    res.status(500).json({
      error: error.message || "Could not cancel order"
    });
  } finally {
    client.release();
  }
});

/* =========================================================
   UPDATE PAYMENT STATUS
   ========================================================= */

app.put(
  "/api/admin/orders/:id/payment-status",
  adminAuth,
  async (req, res) => {
    try {
      const orderId = cleanText(req.params.id);
      const paymentStatus = cleanText(req.body?.paymentStatus);

      if (!PAYMENT_STATUSES.includes(paymentStatus)) {
        return res.status(400).json({
          error: "Invalid payment status"
        });
      }

      const result = await pool.query(
        `
        UPDATE orders
        SET payment_status = $1,
            updated_at = NOW()
        WHERE id = $2
        RETURNING
          id::text AS id,
          payment_status AS "paymentStatus"
        `,
        [paymentStatus, orderId]
      );

      if (!result.rows.length) {
        return res.status(404).json({
          error: "Order not found"
        });
      }

      res.json({
        ok: true,
        order: result.rows[0]
      });
    } catch (error) {
      console.error("Update payment status error:", error);
      res.status(500).json({
        error: error.message || "Could not update payment status"
      });
    }
  }
);

/* =========================================================
   PUBLIC ORDER TRACKING
   ========================================================= */

app.get("/api/orders/:id", async (req, res) => {
  try {
    const orderId = cleanText(req.params.id);

    const result = await pool.query(
      `
      SELECT
        id::text AS id,
        created_at AS "createdAt",
        customer,
        items,
        total::float AS total,
        payment_method AS "paymentMethod",
        status,
        payment_status AS "paymentStatus",
        stock_restored AS "stockRestored",
        updated_at AS "updatedAt"
      FROM orders
      WHERE id = $1
      `,
      [orderId]
    );

    if (!result.rows.length) {
      return res.status(404).json({
        error: "Order not found"
      });
    }

    res.json({
      ok: true,
      order: result.rows[0]
    });
  } catch (error) {
    console.error("Order tracking error:", error);
    res.status(500).json({
      error: error.message || "Could not load order"
    });
  }
});

/* =========================================================
   CREATE ORDER
   ========================================================= */

app.post("/api/orders", async (req, res) => {
  const client = await pool.connect();

  try {
    const body = req.body || {};
    const customer = body.customer;
    const items = body.items;

    const paymentMethod =
      cleanText(body.paymentMethod, "cod") || "cod";

    if (
      !customer ||
      !cleanText(customer.name) ||
      !cleanText(customer.phone) ||
      !cleanText(customer.address)
    ) {
      return res.status(400).json({
        error: "Customer information is required"
      });
    }

    if (!Array.isArray(items) || items.length === 0) {
      return res.status(400).json({
        error: "Order items are required"
      });
    }

    await client.query("BEGIN");

    const quantityMap = new Map();

    for (const item of items) {
      const id = cleanText(item?.id);
      const qty = Math.max(1, nonNegativeInt(item?.qty, 1));

      if (!id) {
        throw new Error("Invalid product ID");
      }

      quantityMap.set(
        id,
        (quantityMap.get(id) || 0) + qty
      );
    }

    let total = 0;
    const cleanItems = [];

    for (const [productId, qty] of quantityMap) {
      const result = await client.query(
        `
        SELECT
          id::text AS id,
          name,
          price::float AS price,
          stock
        FROM products
        WHERE id = $1
        FOR UPDATE
        `,
        [productId]
      );

      if (!result.rows.length) {
        throw new Error(`Product not found: ${productId}`);
      }

      const product = result.rows[0];

      if (Number(product.stock) < qty) {
        throw new Error(
          `Not enough stock for ${product.name}`
        );
      }

      const price = Number(product.price);
      total += price * qty;

      cleanItems.push({
        id: String(product.id),
        name: product.name,
        price,
        qty
      });
    }

    total = Math.round(total * 100) / 100;

    const orderId = makeOrderId();

    const cleanCustomer = {
      name: cleanText(customer.name),
      phone: cleanText(customer.phone),
      address: cleanText(customer.address)
    };

    await client.query(
      `
      INSERT INTO orders
        (
          id,
          created_at,
          customer,
          items,
          total,
          payment_method,
          status,
          payment_status,
          stock_restored,
          updated_at
        )
      VALUES
        ($1, NOW(), $2::jsonb, $3::jsonb, $4, $5, 'Pending',
         'Pending', FALSE, NOW())
      `,
      [
        orderId,
        JSON.stringify(cleanCustomer),
        JSON.stringify(cleanItems),
        total,
        paymentMethod
      ]
    );

    for (const item of cleanItems) {
      const stockUpdate = await client.query(
        `
        UPDATE products
        SET stock = stock - $1,
            updated_at = NOW()
        WHERE id = $2
          AND stock >= $1
        `,
        [item.qty, item.id]
      );

      if (stockUpdate.rowCount !== 1) {
        throw new Error(
          `Stock changed while placing order for ${item.name}. Please try again.`
        );
      }
    }

    await client.query("COMMIT");

    res.status(201).json({
      ok: true,
      orderId,
      total,
      status: "Pending",
      paymentStatus: "Pending"
    });
  } catch (error) {
    await client.query("ROLLBACK").catch(() => {});
    console.error("Order error:", error);

    res.status(400).json({
      error: error.message || "Could not create order"
    });
  } finally {
    client.release();
  }
});

/* =========================================================
   PAYMENT PLACEHOLDER
   ========================================================= */

app.post("/api/payment/create", (req, res) => {
  const method = cleanText(req.body?.method);

  if (!["bkash", "nagad", "card"].includes(method)) {
    return res.status(400).json({
      error: "Unsupported payment method"
    });
  }

  res.status(501).json({
    error: `${method} payment gateway is not configured yet.`
  });
});

/* =========================================================
   ADMIN PAGE
   ========================================================= */

app.get("/admin", (req, res) => {
  const adminFile = path.join(__dirname, "public", "admin.html");

  if (fs.existsSync(adminFile)) {
    return res.sendFile(adminFile);
  }

  res.status(404).send("Admin page not found");
});

/* =========================================================
   WEBSITE FALLBACK
   ========================================================= */

app.use((req, res, next) => {
  if (req.method === "GET" && !req.path.startsWith("/api/")) {
    const indexFile = path.join(
      __dirname,
      "public",
      "index.html"
    );

    if (fs.existsSync(indexFile)) {
      return res.sendFile(indexFile);
    }
  }

  next();
});

/* =========================================================
   404
   ========================================================= */

app.use((req, res) => {
  res.status(404).json({
    error: "Not found"
  });
});

/* =========================================================
   GLOBAL ERROR HANDLER
   ========================================================= */

app.use((error, req, res, next) => {
  console.error("Unhandled server error:", error);

  if (res.headersSent) {
    return next(error);
  }

  res.status(500).json({
    error: "Internal server error"
  });
});

/* =========================================================
   START SERVER
   ========================================================= */

async function startServer() {
  try {
    await initDatabase();

    app.listen(PORT, "0.0.0.0", () => {
      console.log(
        `SM Online Shop running on port ${PORT}`
      );
    });
  } catch (error) {
    console.error(
      "Server startup failed:",
      error
    );
    process.exit(1);
  }
}

startServer();

/* =========================================================
   GRACEFUL SHUTDOWN
   ========================================================= */

async function shutdown(signal) {
  console.log(`${signal} received. Closing server...`);

  try {
    await pool.end();
  } catch (error) {
    console.error("Pool shutdown error:", error);
  }

  process.exit(0);
}

process.on("SIGTERM", () => shutdown("SIGTERM"));
process.on("SIGINT", () => shutdown("SIGINT"));

